### ISSUE TITLE
Publish solutions for R-Lab sessions?

### ISSUE THREAD

**Issue by Throvn** [Leoniepopken/SBA#1]
Hey Leonie,
I just wanted to ask if we should also contribute the solutions of the R-Labs.

Additionally, I think an R cheat sheet would be a great idea to add to this repo.

Best regards,
Louis :)

**Comment by Leoniepopken** [comment]
Hi Louis!

I'm honestly not sure if we're allowed to publish the solutions in this repository...

The idea of a R cheat sheet is nice! I am working on it...if you want you can help me :D I am happy about every help on this repository.

Have a nice day,
Leonie

**Comment by Throvn** [comment]
Thanks for your quick reply, I will probably open a pull request in the next few days.
I am a bit busy rn but I think I will find some time on the weekend to also add some R scripts :)
