### ISSUE TITLE
Adding Link to the sidebar

### ISSUE THREAD

**Issue by Throvn** [Leoniepopken/SBA#12]
Hey Leonie, just a quick suggestion :)
If you are on the repositories 'homepage' you could add the link of the website in the sidebar.
It is just a minor thing, but I got used to searching for the link there haha.

1. On the homepage click the little settings wheel next to about on the right side.
2. Paste the link: https://leoniepokpen.github.io/SBA/
3. Save the changes.

I tried to do this but apparently maintainers still have no permissions to change the settings.

**Comment by Leoniepopken** [comment]
Hi Louis! Of course :D It's done!
