### ISSUE TITLE
Change of Design

### ISSUE THREAD

**Issue by Throvn** [Leoniepopken/SBA#3]
Hey Leonie, it's me again :)

Today I have a little bit of free time and would like to continue working on this repo.
I have further thought about how to improve it.
Tbh, github is a great place for code, but (I think) most of the SBA students cannot grasp the concept of it.
My suggestion: Why not host this repo on gh pages? (its free!)
The two main advantages would be 1) Huge improvement of accessibility and 2) we could host r-notebooks and use LaTeX notation in the files.

However, before I start working on it I would wait for your response since it's a rather big change and I wanted to hear your thoughts first.

**Comment by Leoniepopken** [comment]
Hi Louis! You are totally right :D and I think it is a good idea. Would the code still be available on github? Do you maybe have a example how it would look afterwards?

**Comment by Throvn** [comment]
Yes, the code would still be avaliable on github. The only thing that would change is that we would add a few HTML/CSS files blah to the repo. I mean I haven't started working on it but basically, I would now. I would start with a REALLY basic table of contents file (even without CSS) and then we can upgrade the design later. I think we should improve it in small steps :)

Example (out of context):
This has nothing to do with Statistics but it is the same principle: https://throvn.github.io/sorting-vizualizations/
And this is the corresponding repo: https://github.com/Throvn/sorting-visualizations 
Everything we push to the repo will then also be statically hosted and as soon as the repo is updated the website is too.

And btw. It would be nice for me if you could add me as a collaborator for this :D Then I can change the settings to turn this repo into a webpage.

**Comment by Leoniepopken** [comment]
Sounds really good, thank you so much for your help! :D

**Comment by Leoniepopken** [comment]
Hi Louis! Unfortunately I am unalble to run the code so I can test the website. Where do you write the code? And how do you get it on the website?
